---
- name: Configure EC2 instance with Docker, Docker Compose, and Node.js
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: Install Node.js and npm
      ansible.builtin.shell:
        cmd: |
          curl -sL https://deb.nodesource.com/setup_22.x | bash -
          apt-get install -y nodejs
        creates: /usr/bin/node

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

        
    - name: Copy Docker Compose file for Jenkins and SonarQube
      copy:
        src: ./docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml


    - name: Run Docker Compose to start Jenkins and SonarQube
      docker_compose:
        project_src: /home/ubuntu
        state: present
        restarted: yes
        # build: yes
        

    - name: Verify Docker Compose services are running
      command: docker-compose ps
      args:
        chdir: /home/ubuntu
      register: docker_compose_status

    - name: Output Docker Compose status
      debug:
        var: docker_compose_status.stdout_lines

